<div>
    <h1>Legal</h1>
    <center><p>Last Updated on 12 November 2023</p></center>
    <center><p>THESE RULES ARE SUBJECT TO CHANGE</p></center>
    <h2>Disclaimer</h2>
    <article>
        <h3>1. Medical Advice:</h3>
        HealthLink provides a platform for connecting with healthcare professionals,
        but the information provided should not be considered a substitute for professional
        medical advice, diagnosis, or treatment.

        <h3>2. Use of OpenAI:</h3>
        Our platform may utilize OpenAI for certain features, and users should be
        aware that responses generated by OpenAI are based on data available up to
        the knowledge cutoff date and may not always reflect the most recent medical
        advancements.

        <h3>3. Platform Availability:</h3>
        We strive to maintain the availability and accuracy of our platform but do
        not guarantee uninterrupted access or error-free operation.

        <h3>4. Limitation of Liability:</h3>
        HealthLink disclaims any liability for the acts or omissions of healthcare
        professionals on the platform and does not endorse or guarantee the quality
        of services provided.
    </article>
    <h2>Terms and Conditions</h2>
    <article style="color:black">
        <h3>1. Acceptance of Terms:</h3>
        By accessing or using the HealthLink platform ("HealthLink," "we," "us," or "our"), you agree to comply with and be bound by these Terms of Service ("Terms"). If you do not agree to these terms, please refrain from using our services.

        <h3>2. Use of Services:</h3>
        HealthLink provides an online platform connecting users with healthcare professionals. You agree to use the services responsibly, respecting the rights and well-being of others. By using HealthLink, you acknowledge that the platform facilitates communication between users and healthcare professionals and is not a substitute for professional medical advice.

        <h3>3. Eligibility:</h3>
        You must be at least 18 years old or have the consent of a legal guardian
        to use HealthLink. Users under 18 should only use the platform under the
        supervision of a parent or guardian.
        <h3>4. Registration and User Accounts:</h3>
        To access certain features of HealthLink, you may be required to register and create a user account. You agree to provide accurate and current information during the registration process and to update such information to keep it accurate and current.
        <h3>5. User Responsibilities:</h3>
        Users are responsible for maintaining the confidentiality of their account credentials and for all activities that occur under their account. You agree to notify us immediately of any unauthorized use of your account or any other breach of security.
        <h3>6. Privacy and Data Usage:</h3>
        Your use of HealthLink is also governed by our Privacy Policy, which outlines how we collect, use, and protect your personal information in compliance with the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011. By using HealthLink, you consent to the collection, processing, and transfer of your personal information in accordance with this Privacy Policy.
        <h3>7. Intellectual Property:</h3>
        HealthLink and its content, including but not limited to text, graphics, logos, images, and software, are protected by intellectual property laws. You may not use, reproduce, or distribute any part of our platform without explicit permission.

        <h3>8. Termination:</h3>
        HealthLink reserves the right to terminate or suspend your access to the platform at any time for violations of these terms or for any other reason. In the event of termination, the provisions of these Terms regarding intellectual property, disclaimers, limitations of liability, and the indemnification of HealthLink shall survive.

        <h3>9. Limitation of Liability:</h3>
        HealthLink, its affiliates, and partners shall not be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use or inability to use our services. You agree that your use of HealthLink is at your sole risk.

        <h3>10. Dispute Resolution:</h3>
        Any disputes arising under or in connection with these Terms of Service shall be subject to the exclusive jurisdiction of the courts in Bangalore,Karnataka, India. The laws of India shall govern these Terms, and you hereby consent to the exclusive jurisdiction and venue of the courts in Bangalore,Karnataka, India.
        <h3>11. Amendments to Terms:</h3>
        HealthLink reserves the right to modify or amend these Terms at any time. Any changes will be effective immediately upon posting on the HealthLink website. Your continued use of the platform after such changes will constitute your acceptance of the revised Terms.
    </article>
    <h2>Privacy Policy</h2>
    <article>
        <h3>1. Information Collection:</h3>
        HealthLink collects personal information, including but not limited to, user
        profiles, chat data, and device information. This data is used to provide
        and improve our services in accordance with the Information Technology (Reasonable
        Security Practices and Procedures and Sensitive Personal Data or Information)
        Rules, 2011.

        <h3>2. Data Storage and Security:</h3>
        We utilize Firebase for data storage and processing, and your data is securely
        stored and protected. We implement reasonable security measures to prevent
        unauthorized access.

        <h3>3. Third-Party Services:</h3>
        HealthLink may use third-party services, including OpenAI, to enhance our
        platform. These services have their own privacy policies, and we encourage
        users to review them.

        <h3>4. Cookies and Tracking:</h3>
        We use cookies and similar technologies to enhance user experience. Users
        can manage cookie preferences through their browser settings.

        <h3>5. User Consent:</h3>
        By using HealthLink, you consent to the collection, processing, and transfer
        of your personal information in accordance with this Privacy Policy.

        <h3>6. Changes to Privacy Policy:</h3>
        HealthLink may update this Privacy Policy to reflect changes in our practices.
        Users will be notified of significant changes.

        <h3>7. Contact Information:</h3>
        For any queries or concerns regarding these legal documents, please contact
        us at [healthlink@mtt.one].
    </article>
</div>

<style>
    h1,
    h2 {
        text-align: center;
        font-weight: bold;
    }
    article{
        font-size: 14px;
    }
    div{
    color: black;
    width: 100%;
    height:500%;
    background-image: linear-gradient(
                rgba(206, 252, 241, 0.9),
                rgba(244, 222, 255, 0.9)
            ),
            url(bgvev1.png);
  }
</style>
